services:
  enhancer:
    build: .
    container_name: video-enhancer
    volumes:
      - ./Video:/app/Video
      - venv_data:/pyvenv
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  venv_data: